add Antithesis as a member
opensourcepledge/osspledge.com pull request #111
Opened 2024-09-13 20:06 UTC by guergabo

The blog post and links to JSON file will go live Sep 16. 

Branding materials: https://www.antithesis.com/brand/

2024-09-13 20:11 UTC, vladh commented
Thank you! We’ll look out for the JSON file and review when it’s available. Excited to have you on board! 🐛

2024-09-16 18:32 UTC, vladh requested changes
Could we have `urlLearnMore` point to the blog post instead of the homepage? Just because the `urlLearnMore` page should say something about the member's contributions to Open Source.

2024-09-16 18:32 UTC, vladh commented
I left one small comment, but this looks good to me otherwise! I'll wait for a second review before merging.

2024-09-16 22:55 UTC, chadwhitacre commented
Everyone else has prepended instead of appended. Do we care?

2024-09-16 23:49 UTC, vladh commented
> Everyone else has prepended instead of appended. Do we care?

I don't think it matters — we can just sort them alphabetically later. 😛

2024-09-16 23:50 UTC, chadwhitacre commented
Or move them to a database. 🙃

2024-09-16 23:51 UTC, chadwhitacre commented
I'm good with this once the change you requested is made. 👍

2024-09-17 15:07 UTC, guergabo commented
Hi @vladh, I pushed the changes. They should be live now. LMK if all good. Thanks!

2024-09-17 16:09 UTC, vladh commented
@guergabo Err, sorry, I just noticed that your `averageNumberOfDevs` is `8086`. I'm assuming you don't have 8086 developers employed — did you mean 23?

2024-09-17 16:22 UTC, guergabo commented
I made the changes. Should be live EOD.

2024-09-17 16:27 UTC, vladh commented
Gotcha, thank you! :)

2024-09-18 03:05 UTC, guergabo commented
Hi @vladh, this should be to go now. Thanks!

2024-09-18 09:05 UTC, merged

2024-09-18 09:05 UTC, vladh commented
@guergabo Welcome on board! 🎈 

One small request: could you please change “The OSS pledge initiative” in your blog post to say “The Open Source Pledge initiative”? The name of the initiative is “Open Source Pledge” and the domain is “osspledge.com” — maybe we should have made the domain “opensourcepledge.com” to avoid confusion.

Thanks for your work on these small changes!

2024-09-23 16:29 UTC, guergabo commented
> @guergabo Welcome on board! 🎈 https://osspledge.com/members/antithesis/
> 
> One small request: could you please change “The OSS pledge initiative” in your blog post to say “The Open Source Pledge initiative”? The name of the initiative is “Open Source Pledge” and the domain is “osspledge.com” — maybe we should have made the domain “opensourcepledge.com” to avoid confusion.
> 
> Thanks for your work on these small changes!

Hi @vladh, sorry for the delay. I was OOO for a bit. I made the change you requested. Should be live some time tomorrow. Thanks !

2024-09-23 16:32 UTC, vladh commented
Thanks @guergabo! We've also changed the domain to opensourcepledge.com in the meantime to avoid confusion. :)