Add HTTP Toolkit to members.csv
opensourcepledge/osspledge.com pull request #41
Opened 2024-08-06 16:26 UTC by pimterry

Adding HTTP Toolkit to the members list :smiley:

The README says "Include links to your branding materials" - unclear exactly what materials you'd like, but here's a selection:

* [High res logo with transparent background](https://github.com/user-attachments/assets/fd572f77-e80f-4a16-b4f2-43879afcd920)
* [Logo + text with transparent background](https://github.com/user-attachments/assets/2af626f6-94e7-49de-9165-2a03ea135ac0)
* [Full brand book](https://github.com/user-attachments/files/16512994/Http.Toolkit.-.Brand.Guidelines.pdf)

This doesn't match the current website yet, there's a pending brand update that I'll be rolling out in just a few weeks which tweaks things in a few places, but it'll all match up nicely soon. I have no problem with these being published & visible in places before that's live, but if you'd prefer current materials in the meantime let me know.

2024-08-06 16:49 UTC, vladh commented
Thank you for this @pimterry! So cool to have you as the first member. Let me work out a CI issue and I'll get this merged. :)

2024-08-07 10:55 UTC, vladh commented
@chadwhitacre To unblock this PR, we need to remove the `main` branch protections on the repo, because they prevent the GitHub runner itself from updating the member JSON files. Silly, but that's apparently how it works.

In any case, the protections are actually not required. The same result can be achieved by only giving push access to the repo to the people currently allowed to override the protections, and requiring everyone else to create a PR based on a fork, which anyone can do anyway.

2024-08-07 21:42 UTC, chadwhitacre commented
Huzzah! 🥳 👏 @pimterry 

@vladh Do you have the permissions you need to make the GitHub configuration changes to unblock this PR? If not let's get you them. :-)

Also it looks like we've got a conflict now on this PR, unfortunately.

2024-08-07 21:44 UTC, vladh commented
@chadwhitacre Nope, I don't have the permissions.

I can fix the conflict, no trouble.

2024-08-07 21:54 UTC, chadwhitacre commented
Try now?

2024-08-07 22:03 UTC, chadwhitacre requested changes
Hey we're talking internally about reporting requirements and such, let's hold off on merging this for a minute while we play out this conversation ... I'll return here soon.

2024-08-07 22:04 UTC, vladh commented
@chadwhitacre No worries! I've fixed the technical issues in the meantime.

2024-08-07 22:19 UTC, dcramer commented
Talking live with chad, but I opened a ticket for more transparency #45

2024-08-27 22:16 UTC, vladh commented
Hey @pimterry, thanks so much for your patience while we ironed some things out.

I've now updated [the README](https://github.com/opensourcepledge/osspledge.com) with the latest version of our reporting requirements.

The main change, I think, is that we expect members to have some kind of blog post on their website explaining the donations they made to open source projects. Ideally, but not strictly necessarily, this would have payments itemised by recipient where possible, and I've created [a tool to help with this for GitHub sponsors payments](https://github.com/opensourcepledge/osp-github-reporter/).

When you have the time, if you could make a blog post then update this PR that would be amazing. ✨ 

Happy to hear your feedback on this!

2024-08-27 22:54 UTC, chadwhitacre commented
> I've now updated [the README](https://github.com/opensourcepledge/osspledge.com) with the latest version of our reporting requirements.

... aaaaaaaaand this has been moved to [osspledge.com/join](https://osspledge.com/join/). 😬 🙇‍♂️

2024-08-28 17:55 UTC, pimterry commented
> When you have the time, if you could make a blog post then update this PR that would be amazing. ✨
> 
> Happy to hear your feedback on this!

I'll try to find some time to put something together for this soon, but I have a lot going on right now and it's going to take a little while to put this together.

That said, I hear the arguments but I'm still not a huge fan of this as a requirement - I'd much rather link contributions to the platforms themselves where possible (more verifiable, and better for those platforms too) and lower barriers.

This is also something that ends up a little weird for organizations who've been donating to open source for a while, if they don't already have these annual reports written & published. It's quite odd to now publicly publish a new "Here's the open source we donated to in 2021" report in 2024, but it seems the intent is that it won't be possible to include those past contributions without doing so.

Anyway, I'll work on putting something together next week if I can, watch this space.

2024-08-28 19:31 UTC, vladh commented
I do get that the blog post requirement introduces friction. It does seem to me that the blog post could be very minimal — a couple of paragraphs and a list of payments.

2024-08-28 19:34 UTC, dcramer commented
@pimterry you dont need to publish in retro (I wouldn't bother at the very least), but without that level of accountability (and the marketing gained from it) the program can't really succeed. If it was just a way to say "here are companies that use open collective" its kind of a waste of time. We really want to basically create almost this social peer pressure amongst organizations where we can overwhelm them with the message, create a sort of FOMO/shame situation if they don't participate, especially if they say they care.

2024-09-03 16:12 UTC, vladh approved these changes
Love your post @pimterry! 🔥

2024-09-03 16:13 UTC, pimterry commented
I've now written up a nice blog post with a proper breakdown at https://httptoolkit.com/blog/open-source-funding-pledge/, updated the JSON linked here (https://httptoolkit.com/data/oss-pledge.json) to the latest format, and rebased on top of the other updates.

I do still mildly disagree on these requirements (agree on peer pressure & accountability goals, sure, but being able to show the largest possible number of peers seems like the key to peer pressure, and there are easy routes to accountability for the common case that don't add friction or exclude orgs who'd contribute to that peer pressure). That said, it's your project, you can set the rules as you'd like - I hope the feedback is useful, but obviously I'm still very much in favor of the whole enterprise in general regardless, it's certainly not a deal breaker.

2024-09-03 16:36 UTC, chadwhitacre commented
Thank you for working with us on this, @pimterry! 🙏

2024-09-03 16:36 UTC, chadwhitacre approved these changes

2024-09-03 16:37 UTC, merged